src/Entity/Leave.php
<?php

namespace App\Entity;

use App\Repository\LeaveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LeaveRepository::class)]
#[ORM\Table(name: '`leave`')]
class Leave
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Leave_from = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Leave_to = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Leave_description = null;

    #[ORM\Column]
    private ?int $Leave_status = null;

    #[ORM\ManyToOne(inversedBy: 'leaves')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'leaves')]
    #[ORM\JoinColumn(nullable: false)]
    private ?LeaveType $leavetype = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $rejectionComment = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $medicalCertificatePath = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLeaveFrom(): ?\DateTimeInterface
    {
        return $this->Leave_from;
    }

    public function setLeaveFrom(\DateTimeInterface $Leave_from): static
    {
        $this->Leave_from = $Leave_from;

        return $this;
    }

    public function getLeaveTo(): ?\DateTimeInterface
    {
        return $this->Leave_to;
    }

    public function setLeaveTo(\DateTimeInterface $Leave_to): static
    {
        $this->Leave_to = $Leave_to;

        return $this;
    }

    public function getLeaveDescription(): ?string
    {
        return $this->Leave_description;
    }

    public function setLeaveDescription(string $Leave_description): static
    {
        $this->Leave_description = $Leave_description;

        return $this;
    }

    public function getLeaveStatus(): ?int
    {
        return $this->Leave_status;
    }

    public function setLeaveStatus(int $Leave_status): static
    {
        $this->Leave_status = $Leave_status;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): static
    {
        $this->employee = $employee;

        return $this;
    }

    public function getLeavetype(): ?LeaveType
    {
        return $this->leavetype;
    }

    public function setLeavetype(?LeaveType $leavetype): static
    {
        $this->leavetype = $leavetype;

        return $this;
    }
    

    // Getter et Setter pour rejectionComment
    public function getRejectionComment(): ?string
    {
        return $this->rejectionComment;
    }

    public function setRejectionComment(?string $rejectionComment): self
    {
        $this->rejectionComment = $rejectionComment;

        return $this;
    }

    //pour le certificat medical
    public function getMedicalCertificatePath(): ?string
    {
        return $this->medicalCertificatePath;
    }

    public function setMedicalCertificatePath(?string $medicalCertificatePath): static
    {
        $this->medicalCertificatePath = $medicalCertificatePath;

        return $this;
    }    

}

src/Entity/LeaveType.php
<?php

namespace App\Entity;

use App\Repository\LeaveTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LeaveTypeRepository::class)]
class LeaveType
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $leave_type = null;

    #[ORM\OneToMany(mappedBy: 'leavetype', targetEntity: Leave::class)]
    private Collection $leaves;

    #[ORM\OneToMany(mappedBy: 'categorieAbsence', targetEntity: Pointage::class)]
    private Collection $pointages;

    public function __construct()
    {
        $this->leaves = new ArrayCollection();
        $this->pointages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLeaveType(): ?string
    {
        return $this->leave_type;
    }

    public function setLeaveType(string $leave_type): static
    {
        $this->leave_type = $leave_type;

        return $this;
    }

    // convertir leavetype en string pour la page leave du tableau de bord d'un employé
    public function __toString(): string
    {
        // Retourne le type de congé pour qu'il puisse être converti en chaîne
        return $this->leave_type;
    }

    /**
     * @return Collection<int, Leave>
     */
    public function getLeaves(): Collection
    {
        return $this->leaves;
    }

    public function addLeaf(Leave $leaf): static
    {
        if (!$this->leaves->contains($leaf)) {
            $this->leaves->add($leaf);
            $leaf->setLeavetype($this);
        }

        return $this;
    }

    public function removeLeaf(Leave $leaf): static
    {
        if ($this->leaves->removeElement($leaf)) {
            // set the owning side to null (unless already changed)
            if ($leaf->getLeavetype() === $this) {
                $leaf->setLeavetype(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Pointage>
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    public function addPointage(Pointage $pointage): static
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages->add($pointage);
            $pointage->setCategorieAbsence($this);
        }

        return $this;
    }

    public function removePointage(Pointage $pointage): static
    {
        if ($this->pointages->removeElement($pointage)) {
            // set the owning side to null (unless already changed)
            if ($pointage->getCategorieAbsence() === $this) {
                $pointage->setCategorieAbsence(null);
            }
        }

        return $this;
    }

}

src/Form/LeaveType.php
<?php

namespace App\Form;

use App\Entity\Leave;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\LeaveType as LeaveTypeEntity; // Alias pour éviter le conflit
use Symfony\Component\Form\Extension\Core\Type\FileType;




class LeaveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            //->add('leavetype', TextType::class, ['label' => 'Type Congé',])
            ->add('leavetype', EntityType::class, [
                'class' => LeaveTypeEntity::class,
                'choice_label' => 'leavetype', // ou tout autre champ de l'entité LeaveType que vous voulez afficher
                'label' => 'Type Congé',
            ])
            ->add('Leave_from', DateType::class, ['label' => 'Début Congé',])
            ->add('Leave_to', DateType::class, ['label' => 'Fin Congé',])
           /* ->add('Leave_description', EntityType::class, [
                'class' => Leave::class,
                'choice_label' => 'Leave_description', // ou tout autre champ de l'entité LeaveType que vous voulez afficher
                'label' => 'Description',
            ])  */
            ->add('Leave_description', TextType::class, [
                'label' => 'Description',
                'required' => false,
                ])
        // champ certificat médical
            ->add('medicalCertificate', FileType::class, [
                'label' => ' ',
                'mapped' => false, // Si le fichier n'est pas directement stocké dans la base de données
                'required' => true,
                'attr' => ['style' => 'display:none;'], // Cachez le champ par défaut
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Leave::class,
        ]);
    }
}

src/Controller/LeaveController.php
<?php

namespace App\Controller;

use App\Entity\Leave;
use App\Form\LeaveType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Component\HttpFoundation\File\Exception\FileException;


class LeaveController extends AbstractController
{

    private $entityManager;
    private $security;

    public function __construct(EntityManagerInterface $entityManager, Security $security)
    {
        $this->entityManager = $entityManager;
        $this->security = $security;
    }


    #[Route('/leave', name: 'leave_index')]
    public function index(): Response
    {
        $user = $this->security->getUser();
    
        // Vérifier si l'utilisateur actuel a un rôle d'admin
        if ($this->isGranted('ROLE_ADMIN')) {
            // Récupérer tous les congés pour les administrateurs
            $leaves = $this->entityManager->getRepository(Leave::class)->findAll();
        } else {
            // Si l'utilisateur est une instance de Employee, alors nous pouvons le récupérer directement
            if ($user instanceof \App\Entity\Employee) {
                $employee = $user;
            } else {
                throw $this->createNotFoundException('Employee entity not found.');
            }
    
            // Récupérer les congés uniquement pour l'employé actuel
            $leaves = $this->entityManager->getRepository(Leave::class)->findBy(['employee' => $employee]);
        }
    
        return $this->render('leave/index.html.twig', [
            'leaves' => $leaves,
        ]);
    }

    



    #[Route('/new', name: 'leave_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $leave = new Leave();
        $form = $this->createForm(LeaveType::class, $leave);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {

                // Assurons-nous que la description n'est pas vide
                if (empty($leave->getLeaveDescription())) {
                    //  définir une valeur par défaut ou refuser la soumission avec un message d'erreur
                    $this->addFlash('error', 'La description de la demande de congé est requise.');
                    return $this->render('leave/new.html.twig', [
                        'form' => $form->createView(),
                    ]);
                }
            
                $medicalCertificateFile = $form->get('medicalCertificate')->getData();
        
                if ($medicalCertificateFile) {
                    $newFilename = uniqid().'.'.$medicalCertificateFile->guessExtension();
                    
                    // Déplacez le fichier dans le répertoire où les certificats médicaux sont stockés
                    try {
                        $medicalCertificateFile->move(
                            $this->getParameter('medical_certificates_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Utilisez la méthode error de l'objet logger pour enregistrer l'erreur
                        $this->logger->error('Erreur de téléchargement du fichier : '.$e->getMessage());

                        // Ajoutez un message flash pour informer l'utilisateur de l'erreur
                        $this->addFlash('error', 'Une erreur s\'est produite lors du téléchargement du certificat médical. Veuillez réessayer.');

                        // Redirigez l'utilisateur vers la page du formulaire ou une autre page appropriée
                        return $this->redirectToRoute('leave_new');                
                    }
        
                    // Utiliser la méthode correcte pour enregistrer le nom du fichier dans la base de données
                    $leave->setMedicalCertificatePath($newFilename);
                } 
            //fin code upload fichier

            // Définir une valeur par défaut pour leave_status si nécessaire
            // Ici, je suppose que le statut "En cours" est représenté par 1
            $leave->setLeaveStatus(1); // cette valeur correspond à celle de "En cours" dans la base de données

            // Obtenez l'utilisateur connecté, qui devrait être une instance de Employee
            $user = $this->security->getUser();
            if (!$user instanceof \App\Entity\Employee) {
                throw $this->createNotFoundException('Connected user is not an employee.');
            }

            // Associez directement l'utilisateur connecté à l'objet Leave
            $leave->setEmployee($user);

            // Continuez avec la persistance et le flush comme avant
            $this->entityManager->persist($leave);
            $this->entityManager->flush();

            return $this->redirectToRoute('leave_index');
        }

        return $this->render('leave/new.html.twig', [
        'form' => $form->createView(),
        ]);

    
    }

    //mise à jour du statut de demande de congé (en cours, approuvé, rejeté)
    #[Route('/leave/update-status/{id}', name: 'leave_update_status', methods: ['POST'])]
    public function updateStatus(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        // Récupérer l'entité Leave en utilisant l'ID
        $leave = $entityManager->getRepository(Leave::class)->find($id);

        // Vérifier si l'entité Leave a été trouvée
        if (!$leave) {
            // Vous pouvez retourner une réponse d'erreur ou lancer une exception
            throw $this->createNotFoundException('No leave found for id '.$id);
        }

        // Récupérer le nouveau statut depuis la requête
        $newStatus = $request->request->get('status');

        // Mettre à jour le statut et sauvegarder les modifications
        if (in_array($newStatus, [1, 2, 3])) {
            $leave->setLeaveStatus($newStatus);
            $entityManager->flush();

            return $this->redirectToRoute('leave_index');
        } else {
            return $this->json(['error' => 'Invalid status'], 400);
        }
    }

//afficher un champs de commentaire après avoir sélectionné rejeté
    #[Route('/leave/update-comment/{id}', name: 'leave_update_comment', methods: ['POST'])]
    public function updateComment(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        $leave = $entityManager->getRepository(Leave::class)->find($id);
        if (!$leave) {
            throw $this->createNotFoundException('No leave found for id '.$id);
        }

        $comment = $request->request->get('rejectionComment');
        if ($comment) {
            $leave->setRejectionComment($comment);
            $entityManager->flush();

            $this->addFlash('success', 'Commentaire mis à jour avec succès.');
        } else {
            $this->addFlash('error', 'Le commentaire ne peut pas être vide.');
        }

        return $this->redirectToRoute('leave_index');
    }



    #[Route('/leave/delete/{id}', name: 'leave_delete', methods: ['POST'])]
    public function delete(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        // Récupérer l'entité Leave en utilisant l'ID
        $leave = $entityManager->getRepository(Leave::class)->find($id);

        // Vérifier si l'entité Leave a été trouvée
        if (!$leave) {
            throw $this->createNotFoundException('No leave found for id '.$id);
        }

        // Vérifier le token CSRF pour sécuriser la suppression
        $submittedToken = $request->request->get('_token');
        if ($this->isCsrfTokenValid('delete'.$id, $submittedToken)) {
            // Supprimer l'entité
            $entityManager->remove($leave);
            $entityManager->flush();

            // Ajouter un message flash pour informer de la suppression
            $this->addFlash('success', 'Le congé a été supprimé avec succès.');
        } else {
            // Gérer l'échec de la vérification CSRF
            $this->addFlash('error', 'Token de sécurité invalide, impossible de supprimer le congé.');
        }

        return $this->redirectToRoute('leave_index');
    }





}

templates/leave/index.html.twig
{# templates/leave/index.html.twig #}
{% extends 'base.html.twig' %}


{% block title %}Liste des congés{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .container {
            max-width: 800px;
            margin: 0 auto;
        }

        .btn-primary {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            text-decoration: none;
        }

        .btn-danger {
            background-color: #dc3545;
            color: #fff;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            text-decoration: none;
        }

        .table {
            width: 100%;
            border-collapse: collapse;/* Cela peut aider à gérer comment les bordures des cellules sont combinées */
            margin-top: 20px;
        }

        .table-responsive {
        display: block;
        width: 100%;
        overflow-x: auto; /* Permet au tableau de défiler horizontalement si nécessaire */
        -webkit-overflow-scrolling: touch; /* Permet le défilement fluide sur les appareils tactiles */
        }


        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 0px;
            text-align: left;
            width: auto; /* Ajustez selon les besoins, ou définissez des largeurs spécifiques pour certaines colonnes */
            overflow: hidden; /* Pour éviter le débordement du texte */
            text-overflow: ellipsis; /* Ajoute des ellipses si le texte déborde */
         {#   white-space: nowrap; /* Empêche le texte de passer à la ligne */ #}
        }
        


        .table th {
            background-color: #f2f2f2;
        }

        .table td:last-child {
            text-align: center;
        }

        textarea {
            width: 100%;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            resize: vertical;
        }

        #rejectionCommentSection {
            display: none;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Liste des congés</h1>
    
    {% if not is_granted('ROLE_ADMIN') %}
    <a href="{{ path('leave_new') }}" class="btn btn-primary">Ajouter un congé</a>
    {% endif %}

<div class="table-responsive"> <!-- Ajouter cette div autour de votre tableau -->

    <table class="table">
        <thead>
            <tr>
                <th>S.No</th>
                <th>ID</th>
                <th>Nom Employé</th> <!-- Nouvelle colonne pour le nom de l'employé -->
                {#<th>Date_Départ</th>#}
                {#<th>Date_Arrivée</th>#}
                <th>Dates de congés</th> <!-- Colonne fusionnée -->
                <th>Type Congé</th>
                <th>Description</th>
                <th>Certificat Médical</th>
                <th>Statut Congé</th>
                <th>Commentaire</th>{# Nouvelle colonne #}

            </tr>
        </thead>
        <tbody>
        {% for leave in leaves %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ leave.id }}</td> 
                <td>{{ leave.employee.name }}</td> <!-- Afficher le nom de l'employé -->
                {#<td>{{ leave.LeaveFrom|date('Y-m-d') }}</td>#}
                {#<td>{{ leave.LeaveTo|date('Y-m-d') }}</td>#}
                <td>Du {{ leave.LeaveFrom|date('Y-m-d') }} au {{ leave.LeaveTo|date('Y-m-d') }} inclus</td> <!-- Afficher les dates de congés fusionnées -->
                <td> {{ leave.leavetype }} </td>
                <td>{{ leave.LeaveDescription }}</td>

                <td>
                        {% if leave.medicalCertificatePath %}
                            <!-- Lien de téléchargement du certificat médical -->
                            <a href="{{ path('download_file', {'filename': leave.medicalCertificatePath}) }}" class="btn btn-primary">Télécharger</a>
                        {% else %}
                            Aucun
                        {% endif %}
                </td>

                <td>
                    
                    {% if is_granted('ROLE_ADMIN') %}
                
                        <form action="{{ path('leave_update_status', {'id': leave.id}) }}" method="post">
                            <select name="status" onchange="this.form.submit()">
                                <option value="1" {% if leave.leaveStatus == 1 %}selected{% endif %}>En cours</option>
                                <option value="2" {% if leave.leaveStatus == 2 %}selected{% endif %}>Approuvé</option>
                                <option value="3" {% if leave.leaveStatus == 3 %}selected{% endif %}>Rejeté</option>
                            </select>
                        </form>
                        
                    {% else %}
                            {% if leave.leaveStatus == 1 %}
                                En cours
                            {% elseif leave.leaveStatus == 2 %}
                                Approuvé
                            {% elseif leave.leaveStatus == 3 %}
                                Rejeté
                            {% endif %}
                
                    {% endif %}

                </td>
                <td>
                    {% if is_granted('ROLE_ADMIN') and leave.leaveStatus == 3 %}
                        <form action="{{ path('leave_update_comment', {'id': leave.id}) }}" method="post">
                            <textarea name="rejectionComment" required>{{ leave.rejectionComment }}</textarea>
                            <button type="submit" class="btn btn-primary">Soumettre</button>
                            <input type="hidden" name="_token" value="{{ csrf_token('update_comment' ~ leave.id) }}">
                        </form>
                    {% else %}
                        {{ leave.rejectionComment ? leave.rejectionComment : '' }}
                    {% endif %}
                </td>


                <td>
                        {# Afficher le bouton de suppression uniquement pour les employés #}
                        {% if not is_granted('ROLE_ADMIN')%}
                        {% if leave.leaveStatus == 1 %}
                
                            <form action="{{ path('leave_delete', {'id': leave.id}) }}" method="post" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce congé ?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ leave.id) }}">
                                <button type="submit" class="btn btn-danger btn-sm">Annuler</button>
                            </form>

                        {% endif %}
                        {% endif %}

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune demande de congé trouvé.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% block javascripts %}
<script>
document.addEventListener('DOMContentLoaded', function () {
    // Assurez-vous que cette sélection correspond à la structure de votre formulaire
    var statusSelectElements = document.querySelectorAll('select[name="status"]');

    statusSelectElements.forEach(function(selectElement) {
        selectElement.addEventListener('change', function() {
            // Trouver le conteneur de commentaire lié à ce sélecteur
            var rejectionCommentSection = this.closest('td').querySelector('#rejectionCommentSection');
            // Afficher ou masquer la section de commentaire basée sur la sélection
            if (this.value === '3') { // Si "Rejeté" est sélectionné
                rejectionCommentSection.style.display = 'block';
            } else {
                rejectionCommentSection.style.display = 'none';
            }
            
        });
    });
});
</script>
{% endblock %}



{% endblock %}

templates/leave/new.html.twig
{# templates/leave/new.html.twig #}
{% extends 'base.html.twig' %}



{% block title %}Nouveau congé{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="mb-4">Demander un nouveau congé</h1>

    {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}

    <div class="form-group">
        {{ form_label(form.Leave_from) }}
        {{ form_widget(form.Leave_from, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.Leave_from) }}
    </div>

    <div class="form-group">
        {{ form_label(form.Leave_to) }}
        {{ form_widget(form.Leave_to, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.Leave_to) }}
    </div>

    <div class="form-group">
        {{ form_label(form.leavetype) }}
        {{ form_widget(form.leavetype, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.leavetype) }}
    </div>

    <div class="form-group">
        {{ form_label(form.Leave_description) }}
        {{ form_widget(form.Leave_description, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.Leave_description) }}
    </div>

    <div class="form-group medical-certificate-field" style="display: none;">
        {{ form_label(form.medicalCertificate) }}
        {{ form_widget(form.medicalCertificate, {'attr': {'class': 'form-control'}}) }}
        <button type="button" class="btn btn-primary" id="medicalCertificateButton">Télécharger Votre Certificat Médical</button>
        {{ form_errors(form.medicalCertificate) }}
    </div>


    <button type="submit" class="btn btn-primary">Envoyer</button>
    {{ form_end(form) }}

    <a href="{{ path('leave_index') }}" class="btn btn-link">Retour</a>
</div>


{% endblock %}

{% block javascripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var leavetypeSelect = document.querySelector('#leave_leavetype');
        var medicalCertificateField = document.querySelector('#leave_medicalCertificate').closest('.form-group');
        
        leavetypeSelect.addEventListener('change', function() {
            //  la valeur ou l'ID correspondant à "Arrêt Maladie"  et autre dans la base de données
            if (this.value == '5'|| this.value == '6') { 
                medicalCertificateField.style.display = 'block';
            } else {
                medicalCertificateField.style.display = 'none';
            }
        });
    });
{# script pour le bouton Télécharger Votre Certificat Médical  #}
    document.getElementById('medicalCertificateButton').addEventListener('click', function() {
        document.getElementById('{{ form.medicalCertificate.vars.id }}').click();
    });
</script>
{% endblock %}




{#
{% block title %}Nouveau congé{% endblock %}

{% block body %}
    <h1>Demander un nouveau congé</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">Envoyer</button>
    {{ form_end(form) }}
{% endblock %} #}